### ISSUE TITLE
Error during cyclinder B-scan plotting example - invalid value encountered in reduce

### ISSUE THREAD

**Issue by TheRealPhoneCall** [gprMax/gprMax#163]
Hi, I'm on mac highsierra 10.13.6 and I was getting gprMax work on it but I encounter this error after following the example plots. I don't see this in any of the issues. Hope you guys can guide me with this, just needed to study BScan.

-------stack trace ---------

$ python3 -m tools.plot_Bscan user_models/cylinder_Bscan_2D_merged.out Ez
Traceback (most recent call last):
  File "/Users/daryl/miniconda3/envs/gprMax/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/daryl/miniconda3/envs/gprMax/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/daryl/Berdware/13_ERGWD/gprMax/tools/plot_Bscan.py", line 92, in <module>
    plthandle = mpl_plot(args.outputfile, outputdata, dt, rx, args.rx_component)
  File "/Users/daryl/Berdware/13_ERGWD/gprMax/tools/plot_Bscan.py", line 48, in mpl_plot
    plt.imshow(outputdata, extent=[0, outputdata.shape[1], outputdata.shape[0] * dt, 0], interpolation='nearest', aspect='auto', cmap='seismic', vmin=-np.amax(np.abs(outputdata)), vmax=np.amax(np.abs(outputdata)))
  File "/Users/daryl/miniconda3/envs/gprMax/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2334, in amax
    initial=initial)
  File "/Users/daryl/miniconda3/envs/gprMax/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
FloatingPointError: invalid value encountered in reduce

**Comment by craig-warren** [comment]
@TheRealPhoneCall I am also running macOS 10.13.6 and the simple B-scan example works OK on my machine. Can I just check a few things:

1. Have you activated the conda environment? From your command prompt it is not clear.
2. Is conda and the gprMax conda environment up to date? If not see the install instructions in the docs.
3. What version of gprMax are you running?
