### ISSUE TITLE
Linux - gcc and CUDA versions

### ISSUE THREAD

**Issue by chaslie** [gprMax/gprMax#208]
hi,
I have bit the bullet and spent all weekend installing linux (I finally got Fedora 30 to work). Fedora 30 comes with gcc version 9.1.1 preinstalled and cuda 10 needs version 8.0.1. I cannot find a way of rolling back to version 8.0.1 and as a result GPRmax will not work with the gpu (see error)

Traceback (most recent call last):
  File "/home/chaslie/anaconda3/envs/gprMax/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/chaslie/anaconda3/envs/gprMax/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chaslie/gprMax/gprMax/__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "/home/chaslie/gprMax/gprMax/gprMax.py", line 66, in main
    run_main(args)
  File "/home/chaslie/gprMax/gprMax/gprMax.py", line 133, in run_main
    gpus, allgpustext = detect_check_gpus(args.gpu)
  File "/home/chaslie/gprMax/gprMax/utilities.py", line 384, in detect_check_gpus
    drv.init()
pycuda._driver.Error: cuInit failed: unknown error

when i check to see if the gpus are recognised they are not. 
how do i fix this????

**Comment by craig-warren** [comment]
Not really a gprMax issue. The fix is make sure the correct gcc compiler version is used with CUDA. I would think you should be able to have multiple versions of gcc installed as long as the correct one is used when gprMax is built.
