### ISSUE TITLE
Error running gprMax

### ISSUE THREAD

**Issue by GokcenMerve** [gprMax/gprMax#227]
Hello,
I installed GprMax correctly. I followed their statements. I have fully installed the libraries and required packages. Frankly, I don't know where to start gprMax. I got this error when I run.

C:\Users\Bozok_Mekatronik4\gprMax-master\lib\Scripts\python.exe C:/Users/Bozok_Mekatronik4/gprMax-master/gprMax/gprMax.py
Traceback (most recent call last):
  File "C:/Users/Bozok_Mekatronik4/gprMax-master/gprMax/gprMax.py", line 31, in <module>
    from gprMax._version import __version__, codename
  File "C:\Users\Bozok_Mekatronik4\gprMax-master\gprMax\gprMax.py", line 31, in <module>
    from gprMax._version import __version__, codename
ModuleNotFoundError: No module named 'gprMax._version'; 'gprMax' is not a package

I would be glad if you help me. Sorry for my bad English.

**Comment by GokcenMerve** [comment]
Yes, I followed the steps on your site. I completed the installation without problems. At the command prompt I ran this code as input to python -m gprMax user_models / cylinder_Ascan_2D.in. It ran smoothly, and when output, the graphs rx1 were displayed.

Our goal is to use gprMax to receive a signal from a subterranean material with a physical device. We would like to obtain a model in hdf5 format and make communication with matlab.
