### ISSUE TITLE
gprMax runtime issue

### ISSUE THREAD

**Issue by GokcenMerve** [gprMax/gprMax#228]
Hello,
I set up according to the steps you shared on your site. But I get this error when I run gprMax in pycharm. 

Traceback (most recent call last):
  File "C:/Users/Bozok_Mekatronik4/gprMax-master/gprMax/gprMax.py", line 31, in <module>
    from gprMax._version import __version__, codename
  File "C:\Users\Bozok_Mekatronik4\gprMax-master\gprMax\gprMax.py", line 31, in <module>
    from gprMax._version import __version__, codename
ModuleNotFoundError: No module named 'gprMax._version'; 'gprMax' is not a package

Process finished with exit code 1

I'd appreciate it if you helped. I'm sorry for my bad english.

**Comment by agianno** [comment]
@GokcenMerve 
This is not a gprMax bug please use our Google forum for questions relating on how to run gprMax. We do not run gprMax via pycharm. It might be possible but you need to find the way to do it. Ask in the forum so other users might be able to help.

**Comment by GokcenMerve** [comment]
Thank you so much.
