### ISSUE TITLE
Materials file for #geometry_objects_read accepts comments only starting with ##

### ISSUE THREAD

**Issue by sir-dio** [gprMax/gprMax#237]
When using the `#geometry_objects_read` with a commented materials file, gprMax raises an IndexError with the following traceback:

```
Traceback (most recent call last):
  File ".../miniconda3/envs/gprMax/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File ".../miniconda3/envs/gprMax/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../gprMax/gprMax/__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File ".../gprMax/gprMax/gprMax.py", line 66, in main
    run_main(args)
  File ".../gprMax/gprMax/gprMax.py", line 188, in run_main
    run_std_sim(args, inputfile, usernamespace)
  File ".../gprMax/gprMax/gprMax.py", line 229, in run_std_sim
    run_model(args, currentmodelrun, modelend - 1, numbermodelruns, inputfile, modelusernamespace)
  File ".../gprMax/gprMax/model_build_run.py", line 187, in run_model
    process_geometrycmds(geometry, G)
  File ".../gprMax/gprMax/input_cmds_geometry.py", line 94, in process_geometrycmds
    singlecmdsimport, multicmdsimport, geometryimport = check_cmd_names(materials, checkessential=False)
  File ".../gprMax/gprMax/input_cmds_file.py", line 213, in check_cmd_names
    cmdparams = cmd[1]
IndexError: list index out of range
```

It disappears when the comment line starts with `## `.
Not a terribly inconvenient behavior, but the comment lines do look quite nicer without the `##`. I did not have time to look into the code and find the reason yet.

**Comment by craig-warren** [comment]
@sir-dio thanks for highlighting this. I think it is fixed in https://github.com/gprMax/gprMax/commit/3345982a49e3ae6c64a95d4caac01106c26d7f0e and would be grateful if you can confirm.

**Comment by sir-dio** [comment]
@craig-warren Tested it, works great now, thanks!
