### ISSUE TITLE
Running gprMax/ test run A-scan

### ISSUE THREAD

**Issue by myouniskhan** [gprMax/gprMax#243]
Please guide me how to fix the issue?

(base) C:\Windows\system32>cd gprmax

(base) C:\Windows\System32\gprMax>conda activate gprMax

(gprMax) C:\Windows\System32\gprMax>python -m gprMax user_models/cylinder_Ascan_
2D.in
Traceback (most recent call last):
  File "C:\Users\laptop\miniconda3\envs\gprMax\lib\runpy.py", line 184,
 in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\laptop\miniconda3\envs\gprMax\lib\runpy.py", line 143,
 in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\laptop\miniconda3\envs\gprMax\lib\runpy.py", line 110,
 in _get_module_details
    __import__(pkg_name)
  File "C:\Windows\System32\gprMax\gprMax\__init__.py", line 11, in <module>
    from .gprMax import api as run
  File "C:\Windows\System32\gprMax\gprMax\gprMax.py", line 37, in <module>
    from gprMax.model_build_run import run_model
  File "C:\Windows\System32\gprMax\gprMax\model_build_run.py", line 44, in <modu
le>
    from gprMax.fields_updates_ext import update_electric
ModuleNotFoundError: No module named 'gprMax.fields_updates_ext'

(gprMax) C:\Windows\System32\gprMax>

**Comment by craig-warren** [comment]
@myouniskhan looks like you haven't built gprMax properly. Can you confirm you followed all the installation steps, and also what machine and operating system you are using.

**Comment by myouniskhan** [comment]
> @myouniskhan looks like you haven't built gprMax properly. Can you confirm you followed all the installation steps, and also what machine and operating system you are using.
Yes, i did it now its working.
thanks alot for your response.
