### ISSUE TITLE
Receive error when operating Bscan

### ISSUE THREAD

**Issue by Isaac-55** [gprMax/gprMax#253]
Traceback (most recent call last):
  File "C:\Users\oo\Miniconda3\envs\gprmax\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\oo\Miniconda3\envs\gprmax\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\oo\Desktop\gprMax\gprMax\__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "C:\Users\oo\Desktop\gprMax\gprMax\gprMax.py", line 66, in main
    run_main(args)
  File "C:\Users\oo\Desktop\gprMax\gprMax\gprMax.py", line 188, in run_main
    run_std_sim(args, inputfile, usernamespace)
  File "C:\Users\oo\Desktop\gprMax\gprMax\gprMax.py", line 229, in run_std_sim
    run_model(args, currentmodelrun, modelend - 1, numbermodelruns, inputfile, modelusernamespace)
  File "C:\Users\oo\Desktop\gprMax\gprMax\model_build_run.py", line 149, in run_model
    singlecmds, multicmds, geometry = check_cmd_names(processedlines)
  File "C:\Users\oo\Desktop\gprMax\gprMax\input_cmds_file.py", line 246, in check_cmd_names
    raise CmdInputError('Your input file is missing essential commands required to run a model. Essential commands are: ' + ', '.join(essentialcmds))
gprMax.exceptions.CmdInputError: Your input file is missing essential commands required to run a model. Essential commands are: #domain, #dx_dy_dz, #time_window

**Comment by craig-warren** [comment]
@Isaac-55 have you read the error message `Your input file is missing essential commands required to run a model. Essential commands are: #domain, #dx_dy_dz, #time_window` and checked your input file?

**Comment by Isaac-55** [comment]
Here is my input file, i thought i have it all the command inside the file. But still produce the same output.


title: B-scan from a serial pipes buried in a dielectric half-space
domain: 3 1 0.002
dx_dy_dz: 0.002 0.002 0.002
time_window: 18e-9

#material: 6 0.01 1 0 my_sand
#material: 3 0.0 1 0 pvc
#material: 2.35 0 1 0 hdpe

waveform: ricker 1 0.8e9 my_ricker
hertzian_dipole: z 1.47 0.90 0 my_ricker
rx: 1.53 0.9 0
src_steps: -0.03 0 0
rx_steps: 0.03 0 0

box: 0 0 0 3 0.9 0.002 my_sand
cylinder: 1.5 0.3 0 1.5 0.3 0.002 0.165 PVC
cylinder: 1.5 0.3 0 1.5 0.3 0.002 0.15 hdpe

**Comment by agianno** [comment]
@Isaac-55  you are missing the '#' symbol from most of your commands. This is not a problem with the code. Use the Users' Forum for questions about correct usage.
