### ISSUE TITLE
Wire dipole antenna model

### ISSUE THREAD

**Issue by p-j-r** [gprMax/gprMax#259]
The [source-code](http://docs.gprmax.com/en/latest/examples_antennas.html) is from gprMax's website. While the input file compiles fine, the plots from output doesn't work.
`**Traceback (most recent call last):**  

  File "/home/paul/anaconda3/envs/gprMax/lib/python3.8/runpy.py", line 194, in _run_module_as_main  
    return _run_code(code, main_globals, None,  
  File "/home/paul/anaconda3/envs/gprMax/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)  
  File "/home/paul/anaconda3/envs/gprMax/lib/python3.8/site-packages/gprMax-3.1.5-py3.8-linux-x86_64.egg/tools/plot_antenna_params.py", line 418, in <module>
    antennaparams = calculate_antenna_params(args.outputfile, args.tltx_num, args.tlrx_num, args.rx_num, args.rx_component)   
  File "/home/paul/anaconda3/envs/gprMax/lib/python3.8/site-packages/gprMax-3.1.5-py3.8-linux-x86_64.egg/tools/plot_antenna_params.py", line 104, in calculate_antenna_params   
    **s11 = np.abs(np.fft.fft(Vref) / np.fft.fft(Vinc))  
FloatingPointError: divide by zero encountered in true_divide`**

Is this due to some error in FFT?

**Comment by craig-warren** [comment]
@p-j-r The divide by zero most likely occurs when the incident voltage (Vinc) goes to zero. I've added a statement for numpy to ignore this when calculating s11, s21, zin, or yin. If you pull the latest code the error should be fixed.

Craig

**Comment by p-j-r** [comment]
Thank you!
