### ISSUE TITLE
Re: Wire antenna dipole

### ISSUE THREAD

**Issue by p-j-r** [gprMax/gprMax#260]
In a previous issue for antenna-dipole, you had suggested pulling and updating; [#259 ]
Now I am getting this!

**Traceback (most recent call last):**
  File "/home/paul/anaconda3/envs/gprMax/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/paul/anaconda3/envs/gprMax/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/paul/anaconda3/envs/gprMax/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/paul/gprMax/gprMax/__init__.py", line 11, in <module>
    from .gprMax import api as run
  File "/home/paul/gprMax/gprMax/gprMax.py", line 37, in <module>
    from gprMax.model_build_run import run_model
  File "/home/paul/gprMax/gprMax/model_build_run.py", line 44, in <module>
    **from gprMax.fields_updates_ext import update_electric
ModuleNotFoundError: No module named 'gprMax.fields_updates_ext'**

**Comment by craig-warren** [comment]
@p-j-r, did you follow these steps for updating? http://docs.gprmax.com/en/latest/include_readme.html#updating-gprmax The error suggests gprMax has not been built and installed properly.

**Comment by p-j-r** [comment]
Oops. conda environment wasn't activated. Thanks; issues are resolved.
