### ISSUE TITLE
Parallel error, mpi, gpu, windows

### ISSUE THREAD

**Issue by rgwangcn** [gprMax/gprMax#301]
**Hello,**

**I have two problems when I use the parallel computation. My questions are listed as follows.**

**=Q1========================================
When I follow steps to run _python -m gprMax user_models/cylinder_Bscan_2D.in -n 60 -mpi 61_ on the anaconda, the following warnings appears. I have installed the MPI .exe and .msi on my windows system and have installed mpi4py in the gprMax environment in anaconda. The warnings are listed as follows**

Traceback (most recent call last):
  File "D:\Miniconda\envs\gprMax\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Miniconda\envs\gprMax\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\gprMax\gprMax\__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "D:\gprMax\gprMax\gprMax.py", line 66, in main
    run_main(args)
  File "D:\gprMax\gprMax\gprMax.py", line 174, in run_main
    run_mpi_sim(args, inputfile, usernamespace)
  File "D:\gprMax\gprMax\gprMax.py", line 403, in run_mpi_sim
    newcomm = comm.Spawn(sys.executable, args=['-m', 'gprMax'] + myargv + [workerflag], maxprocs=numworkers)
  File "mpi4py\MPI\Comm.pyx", line 1931, in mpi4py.MPI.Intracomm.Spawn
mpi4py.MPI.Exception: Internal MPI error!, error stack:
MPI_Comm_spawn(cmd="D:\Miniconda\envs\gprMax\python.exe", argv=0x0000027C09AC6030, maxprocs=60, MPI_INFO_NULL, root=0, MPI_COMM_WORLD, intercomm=0x0000027C09A46660, errors=0x0000000000000000) failed
Internal MPI error!  FAILspawn not supported without process manager

**==Q2==============================================**
**I followed the steps on the website to run the example _python -m gprMax user_models/cylinder_Ascan_2D.in -gpu_ on gpu. But something goes wrong. The warnings are listed as follows**

Traceback (most recent call last):
  File "D:\Miniconda\envs\gprMax\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Miniconda\envs\gprMax\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\gprMax\gprMax\__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "D:\gprMax\gprMax\gprMax.py", line 66, in main
    run_main(args)
  File "D:\gprMax\gprMax\gprMax.py", line 188, in run_main
    run_std_sim(args, inputfile, usernamespace)
  File "D:\gprMax\gprMax\gprMax.py", line 229, in run_std_sim
    run_model(args, currentmodelrun, modelend - 1, numbermodelruns, inputfile, modelusernamespace)
  File "D:\gprMax\gprMax\model_build_run.py", line 373, in run_model
    tsolve, memsolve = solve_gpu(currentmodelrun, modelend, G)
  File "D:\gprMax\gprMax\model_build_run.py", line 508, in solve_gpu
    kernels_fields = SourceModule(kernels_template_fields.substitute(REAL=cudafloattype, COMPLEX=cudacomplextype, N_updatecoeffsE=G.updatecoeffsE.size, N_updatecoeffsH=G.updatecoeffsH.size, NY_MATCOEFFS=G.updatecoeffsE.shape[1], NY_MATDISPCOEFFS=1, NX_FIELDS=G.nx + 1, NY_FIELDS=G.ny + 1, NZ_FIELDS=G.nz + 1, NX_ID=G.ID.shape[1], NY_ID=G.ID.shape[2], NZ_ID=G.ID.shape[3], NX_T=1, NY_T=1, NZ_T=1), options=compiler_opts)
  File "D:\Miniconda\envs\gprMax\lib\site-packages\pycuda\compiler.py", line 349, in __init__
    cubin = compile(
  File "D:\Miniconda\envs\gprMax\lib\site-packages\pycuda\compiler.py", line 298, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "D:\Miniconda\envs\gprMax\lib\site-packages\pycuda\compiler.py", line 87, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "D:\Miniconda\envs\gprMax\lib\site-packages\pycuda\compiler.py", line 58, in preprocess_source
    raise CompileError(
pycuda.driver.CompileError: nvcc preprocessing of C:\Users\14268\AppData\Local\Temp\tmpjt_b8p1t.cu failed
[command: nvcc --preprocess -w -arch sm_75 -m64 -Id:\miniconda\envs\gprmax\lib\site-packages\pycuda\cuda C:\Users\14268\AppData\Local\Temp\tmpjt_b8p1t.cu --compiler-options -EP]

PyCUDA ERROR: The context stack was not empty upon module cleanup.

A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.

**Comment by craig-warren** [comment]
@rgwangcn

**Q1**: It looks like your installation of MPI does not support the MPI Spawn mechanism which gprMax uses by default. There is a no-Spawn approach which you can try, details are here - http://docs.gprmax.com/en/latest/openmp_mpi.html#openmp-mpi-example-no-spawn

**Q2**: What GPU are you using?

**Comment by rgwangcn** [comment]
Thanks for your reply. 
My GPU is NVIDIA GeForce GTX 1660 Ti, the driver version is 30.0.14.7208. 
BTW, I have installed the wsl on my windows system, and solved the gpu computation problem with the wsl.
