### ISSUE TITLE
Some issues about Antenna patterns.

### ISSUE THREAD

**Issue by maydayzzu** [gprMax/gprMax#302]
When I run python -m user_libs.antenna_patterns.plot_fields ，there is an error message:AttributeError: 'Text' object has no property 'frac'.Can boss give some pointers?

**Comment by craig-warren** [comment]
@maydayzzu please post the full traceback to we can look into it.

**Comment by maydayzzu** [comment]
@craig-warren Dear Dr Craig，
Thank you very much for your reply!! I am a Chinese graduate student, so there may be some shortcomings in English expression, please understand^ ^.
So the question is when i want use Antenna patterns，I copied this file（antenna_like_GSSI_1500_patterns_E.in） into a txt（E） file and run: 

> python -m gprMax D:\TKmodel\E.txt -gpu （Although I don't know if it's right)

there are some files generated include E.vti,E_rxsorigin,E.out. Next I run:

> python -m user_libs.antenna_patterns.initial_save  D:\TKmodel\E.out

there is a Written Numpy file: D:\TKmodel\E.npy,next i run:

> python -m user_libs.antenna_patterns.plot_fields D:\TKmodel\E.npy

There are some errors here：
Centre frequency: 1.5 GHz
Critical angle for Er 5 is 27.0 degrees
Wavelength: 0.089 m
Observation distance(s) from 0.100 m (1.1 wavelengths) to 0.300 m (3.4 wavelengths)
Theoretical boundary between reactive & radiating near-field (0.62*sqrt((D^3/wavelength): 0.030 m
Theoretical boundary between radiating near-field & far-field (2*D^2/wavelength): 0.081 m
Traceback (most recent call last):
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\CHY\gprMax\user_libs\antenna_patterns\plot_fields.py", line 106, in <module>
    ax.set_thetagrids(np.arange(0, 360, 30), frac=1.1)
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\site-packages\matplotlib\projections\polar.py", line 1325, in set_thetagrids
    t.update(kwargs)
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\site-packages\matplotlib\text.py", line 172, in update
    super().update(kwargs)
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\site-packages\matplotlib\artist.py", line 1064, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'Text' object has no property 'frac'

So hope to have the guidance of Dr Craig, I would be veryvery happy if I could get help！

Kind regards,
CC

**Comment by craig-warren** [comment]
@maydayzzu this issue was fixed 18 months ago - https://github.com/gprMax/gprMax/commit/3dee01fcf1f37fa8ab51af321fc6678226d5c999

Please make sure you keep you gprMax up to date.
