### ISSUE TITLE
gpu in pycharm

### ISSUE THREAD

**Issue by maydayzzu** [gprMax/gprMax#308]
Dear Dr.Craig,
when i use the command [api(filename, n=num_scan, geometry_only=geo_only, gpu=[0]] in pycharm,there will be the following errors.but it works well on cmd.(mpiexec -n 3 python -m gprMax ......- gpu 0 1).This drives me crazy...

kind regards,
yuan

Traceback (most recent call last):
  File "D:\chy\out.py", line 24, in <module>
    api(filename, n=num_scan, geometry_only=geo_only, gpu=[0])  
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\site-packages\gprmax-3.1.5-py3.9-win-amd64.egg\gprMax\gprMax.py", line 106, in api
    run_main(args)
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\site-packages\gprmax-3.1.5-py3.9-win-amd64.egg\gprMax\gprMax.py", line 189, in run_main
    run_std_sim(args, inputfile, usernamespace)
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\site-packages\gprmax-3.1.5-py3.9-win-amd64.egg\gprMax\gprMax.py", line 230, in run_std_sim
    run_model(args, currentmodelrun, modelend - 1, numbermodelruns, inputfile, modelusernamespace)
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\site-packages\gprmax-3.1.5-py3.9-win-amd64.egg\gprMax\model_build_run.py", line 371, in run_model
    tsolve, memsolve = solve_gpu(currentmodelrun, modelend, G)
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\site-packages\gprmax-3.1.5-py3.9-win-amd64.egg\gprMax\model_build_run.py", line 532, in solve_gpu
    kernelelectricfunc = getattr(import_module(pmlmodulelectric), 'kernels_template_pml_electric_' + G.pmlformulation)
  File "C:\Users\CHY\Anaconda3\envs\gprMax\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gprMax.pml_updates.pml_updates_electric_HORIPML_gpu'
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.

**Comment by craig-warren** [comment]
@maydayzzu the issue here is that when using the API, gprMax can't mind a module `ModuleNotFoundError: No module named 'gprMax.pml_updates.pml_updates_electric_HORIPML_gpu'`. This suggests you missed the install step when installing gprMax, e.g. `python setup.py install`

**Comment by maydayzzu** [comment]
@craig-warren god you are so amazing and awesome！i have newly installed gprmax,and now it works well!verrrrrry thank u~
