### ISSUE TITLE
Error reading h5 file from gprmax

### ISSUE THREAD

**Issue by caucplasf** [gprMax/gprMax#346]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\my_gprmax\gprMax\gprMax\__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "C:\my_gprmax\gprMax\gprMax\gprMax.py", line 69, in main
    run_main(args)
  File "C:\my_gprmax\gprMax\gprMax\gprMax.py", line 191, in run_main
    run_std_sim(args, inputfile, usernamespace)
  File "C:\my_gprmax\gprMax\gprMax\gprMax.py", line 232, in run_std_sim
    run_model(args, currentmodelrun, modelend - 1, numbermodelruns, inputfile, modelusernamespace)
  File "C:\my_gprmax\gprMax\gprMax\model_build_run.py", line 187, in run_model
    process_geometrycmds(geometry, G)
  File "C:\my_gprmax\gprMax\gprMax\input_cmds_geometry.py", line 119, in process_geometrycmds
    data = f['/data'][:]
           ~^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\c7933\anaconda3\envs\gprMax\Lib\site-packages\h5py\_hl\group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'data' doesn't exist)"

**Comment by caucplasf** [comment]
python:
import trimesh
import h5py
import numpy as np
 
PlyPath = "C:\\Users\\c7933\\Desktop\\gpr\\yumili.stl"
mesh = trimesh.load(PlyPath)
v = mesh.vertices
f = mesh.faces
#这样得到的v,f格式是trimesh 内置的格式，不能直接用于其它计算，需要转换为numpy
v = np.array(v)
f = np.array(f)
file= h5py.File('my_object.h5','w')
dx_dy_dz = (0.002, 0.002, 0.002)
# 创建根目录
data_group = file.create_group('type')
# 存储整数数据
v_int = v.astype(np.int32)
f_int = f.astype(np.int32)
data_group.create_dataset('vertices', data=v.astype(np.int16))
data_group.create_dataset('faces', data=f.astype(np.int16))

#int_group = file.create_group('int')
#int_group.create_dataset('vertices', data=v.astype(np.int32))
#int_group.create_dataset('faces', data=f.astype(np.int32))

#data_group = file.create_group(b'data') 
#data_group.create_dataset(b'vertices', data=v.astype(np.int16))
#data_group.create_dataset(b'faces', data=f.astype(np.int16))
file.attrs['dx_dy_dz'] = dx_dy_dz
#group_slice = file['data', :] 

#group = file['data']
#vertices_dataset = group['vertices']
#faces_dataset = group['faces']
#group_slice = group[0:2, 0:2, 0:2]
file.close()

**Comment by craig-warren** [comment]
@caucplasf our docs outline the structure of the HDF5 gprMax requires to read in geometry directly - https://docs.gprmax.com/en/latest/input.html#geometry-objects-read This is basically done by specifying an integer value for each Yee cell which defines which material will be used for that cell.
