### ISSUE TITLE
1 invalid value encountered in sqrt 2 fractal_box_builder error 3 need help

### ISSUE THREAD

**Issue by ysx2023** [gprMax/gprMax#366]
1 
self.sigma.max = (0.8 * (m + 1)) / (config.sim_config.em_consts["z0"] * d * np.sqrt(er * mr))
FloatingPointError: invalid value encountered in sqrt
i met this bug yesterday when i tried to use the "python -m gprMax examples/cylinder_Ascan_2D.in", but today it works 
i found it in PML-building.The er is a negative number，about -19000? i dont remember. Then the error in sqrt occured.
2 
The fractal_box_builder error occured in my 1.in file. it works when i use the gprmax 3.1.6 but does not work in gprmax v4 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\my_gprmax\gprMax-devel\gprMax\__main__.py", line 6, in <module>
    gprMax.gprMax.cli()
  File "D:\my_gprmax\gprMax-devel\gprMax\gprMax.py", line 195, in cli
    results = run_main(args)
              ^^^^^^^^^^^^^^
  File "D:\my_gprmax\gprMax-devel\gprMax\gprMax.py", line 224, in run_main
    results = context.run()
              ^^^^^^^^^^^^^
  File "D:\my_gprmax\gprMax-devel\gprMax\contexts.py", line 79, in run
    model.build()
  File "D:\my_gprmax\gprMax-devel\gprMax\model_build_run.py", line 74, in build
    self.reuse_geometry() if config.get_model_config().reuse_geometry else self.build_geometry()
                                                                           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\my_gprmax\gprMax-devel\gprMax\model_build_run.py", line 142, in build_geometry
    self.build_scene()
  File "D:\my_gprmax\gprMax-devel\gprMax\model_build_run.py", line 268, in build_scene
    scene.create_internal_objects(self.G)
  File "D:\my_gprmax\gprMax-devel\gprMax\scene.py", line 143, in create_internal_objects
    self.process_cmds(self.geometry_cmds, G, sort=False)
  File "D:\my_gprmax\gprMax-devel\gprMax\scene.py", line 91, in process_cmds
    obj.create(grid, uip)
  File "D:\my_gprmax\gprMax-devel\gprMax\cmds_geometry\fractal_box_builder.py", line 401, in create
    volume.fractalvolume[i, j, k] = volume.mixingmodel.matID[int(numberinbin)]
                                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
3 
could you tell me how to use the "Sub-gridding - the ability to define different spatial resolutions in different areas of the main grid. This allows high-dielectric materials and fine geometries to be more efficiently modelled."? i didnt find a doc or an example 
[1.txt](https://github.com/gprMax/gprMax/files/12257444/1.txt)

**Comment by craig-warren** [comment]
@ysx2023 thanks for your comments. There are 3 separate issues/questions here, and it would be better to separate them. Can you file separate issues for 1) and 2) and post 3) in our Google Group (https://groups.google.com/g/gprmax)
