### ISSUE TITLE
how to use #python #end_python

### ISSUE THREAD

**Issue by WHATABLOCK** [gprMax/gprMax#440]
When I try to run the following code, an issue occurs：
#python:   
from gprMax.input_cmd_funcs import *
import numpy as np
for x in range(0, 8):
    name = "my_regolith" + str(x)
    i = np.random.uniform(2.32, 3.491)
    print(f"#material:{i},0,1,0,{name}")
#end_python:     

issue：Processing geometry related cmds:   0%|                                                        | 0/1 [00:00<?, ?cmds/s]
Traceback (most recent call last):
  File "D:\Miniconda\Mini\envs\gprMax\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Miniconda\Mini\envs\gprMax\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Miniconda\Mini\envs\gprMax\lib\site-packages\gprmax-3.1.7-py3.10-win-amd64.egg\gprMax\__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "D:\Miniconda\Mini\envs\gprMax\lib\site-packages\gprmax-3.1.7-py3.10-win-amd64.egg\gprMax\gprMax.py", line 69, in main
    run_main(args)
  File "D:\Miniconda\Mini\envs\gprMax\lib\site-packages\gprmax-3.1.7-py3.10-win-amd64.egg\gprMax\gprMax.py", line 191, in run_main
    run_std_sim(args, inputfile, usernamespace)
  File "D:\Miniconda\Mini\envs\gprMax\lib\site-packages\gprmax-3.1.7-py3.10-win-amd64.egg\gprMax\gprMax.py", line 232, in run_std_sim
    run_model(args, currentmodelrun, modelend - 1, numbermodelruns, inputfile, modelusernamespace)
  File "D:\Miniconda\Mini\envs\gprMax\lib\site-packages\gprmax-3.1.7-py3.10-win-amd64.egg\gprMax\model_build_run.py", line 187, in run_model
    process_geometrycmds(geometry, G)
  File "D:\Miniconda\Mini\envs\gprMax\lib\site-packages\gprmax-3.1.7-py3.10-win-amd64.egg\gprMax\input_cmds_geometry.py", line 96, in process_geometrycmds
    singlecmdsimport, multicmdsimport, geometryimport = check_cmd_names(materials, checkessential=False)
  File "D:\Miniconda\Mini\envs\gprMax\lib\site-packages\gprmax-3.1.7-py3.10-win-amd64.egg\gprMax\input_cmds_file.py", line 219, in check_cmd_names
    raise CmdInputError('There must be a space between the command name and parameters in ' + processedlines[lindex])
gprMax.exceptions.CmdInputError: There must be a space between the command name and parameters in #python:{materials}

**Comment by craig-warren** [comment]
@WHATABLOCK as the error message suggests it looks like you have omitted a space when printing your list of materials, e.g. you have #material:2.32 and you need #material: 2.32 ......

**Comment by HarshJoshi009** [comment]
// try this

from gprMax.input_cmd_funcs import *
import numpy as np

for x in range(0, 8):
    name = "my_regolith" + str(x)
    i = np.random.uniform(2.32, 3.491)
    print(f"#material: {i},0,1,0,{name}")  // Added space after '#material: '
