### ISSUE TITLE
Bscan error

### ISSUE THREAD

**Issue by sohn6124** [gprMax/gprMax#56]
Please check it.

[gprMax] C:\Users\USER\Desktop\gprMax-v.3.0.0b30>python -m tools.plot_Bscan user_models/cylinder_Bscan_2d_merged.out Ez
Traceback (most recent call last):
  File "C:\Users\USER\Miniconda3\envs\gprMax\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\USER\Miniconda3\envs\gprMax\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\Desktop\gprMax-v.3.0.0b30\tools\plot_Bscan.py", line 117, in <module>
    outputdata, dt = get_output_data(args.outputfile, rx, args.rx_component)
AttributeError: 'Namespace' object has no attribute 'rx_component'

**Comment by craig-warren** [comment]
@sohn6124 Thanks for spotting this. Fixed in master branch and latest release (v3.0.0b31).
