### ISSUE TITLE
About Installation

### ISSUE THREAD

**Issue by fanciedgpr** [gprMax/gprMax#78]
Hi Craig,
 I have reinstalled gprMax in my new computer, but after finished I tested the plot_Ascan, the software cann't plot the ascan and printed the following info:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**## (gprMax) D:\gprMax>python -m tools.plot_Ascan user_models/cylinder_Ascan_2D.out

Traceback (most recent call last):
  File "C:\Miniconda3\envs\gprMax\lib\runpy.py", line 184, in _run_module_as_mai
n
    "__main__", mod_spec)
  File "C:\Miniconda3\envs\gprMax\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\gprMax\tools\plot_Ascan.py", line 231, in <module>
    plt = mpl_plot(args.outputfile, args.outputs, fft=args.fft)
  File "D:\gprMax\tools\plot_Ascan.py", line 165, in mpl_plot
    raise CmdInputError('Output(s) requested to plot: {}, but available output(s
) for receiver {} in the file: {}'.format(', '.join(outputs), rx, ', '.join(avai
lableoutputs)))
gprMax.exceptions.CmdInputError: Output(s) requested to plot: Ex, Ey, Ez, Hx, Hy
, Hz, Ix, Iy, Iz, but available output(s) for receiver 1 in the file: Ex, Ey, Ez
, Hx, Hy, Hz**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Would you please tell me why? Thank you!

**Comment by craig-warren** [comment]
Sorry I made some changes to the default outputs that get plotted with an Ascan a few days ago. I introduced a small bug. It is now fixed, so if you pull/download from the master branch the plotting will now work.

Craig

**Comment by fanciedgpr** [comment]
@craig-warren
Ok, thank you!
