### ISSUE TITLE
Running gprMax -- First example

### ISSUE THREAD

**Issue by ChristinB** [gprMax/gprMax#97]
@craig-warren 

I just started using gprMax with Python and cloned it today. When I tried to run plot_AScan.py, I got the message, that detect_gpus is missing. Can you help me out here?

When I removed the import of detect_gpus I received this Error:

-bash-4.2$ python -m tools.plot_Ascan user_models/cylinder_Ascan_2D.out
Traceback (most recent call last):
  File "/apps/gent/CO7/sandybridge/software/Python/3.5.2-intel-2016b/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/apps/gent/CO7/sandybridge/software/Python/3.5.2-intel-2016b/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/user/home/gent/vsc421/vsc42149/.local/lib/python3.5/site-packages/gprMax-3.0.19-py3.5-linux-x86_64.egg/tools/plot_Ascan.py", line 28, in <module>
    from gprMax.exceptions import CmdInputError
  File "/vscmnt/gent_vulpix/_/user/home/gent/vsc421/vsc42149/gprMax/gprMax/gprMax.py", line 31, in <module>
    from gprMax._version import __version__, codename
ImportError: No module named 'gprMax._version'; 'gprMax' is not a package

Can you also help me out here?

Thanks in advance!
Kind regards,
Christin

**Comment by craig-warren** [comment]
@ChristinB Yep, the 'detect_gpus' import should not be there (I'm not sure why you received the second error). I've removed the import, so if you pull from master or clone again, everything should be OK.

Kind regards,
Craig

**Comment by ChristinB** [comment]
Thank you very much! I can run the first example now!
